version: "2"
volumes:
    db1_data:
        external: false
    db2_data:
        external: false
services:
    engine:
        image: kevinjqiu/nylas-sync-engine
        links:
            - redis:redis
            - db1:db1
            - db2:db2
        volumes:
            - ./sync-engine:/app
            - ./data/inboxapp:/var/lib/inboxapp
            - ./config:/etc/inboxapp
        #command: sh -c "bin/create-db && bin/inbox-start"
        command: bin/inbox-start
        environment:
            FIRST_RUN: 0  # need to run bin/create-db if FIRST_RUN
    api:
        image: kevinjqiu/nylas-sync-engine
        links:
            - redis:redis
            - db1:db1
            - db2:db2
        ports:
            - "5555:5555"
        volumes:
            - ./sync-engine:/app
            - ./data/inboxapp:/var/lib/inboxapp
            - ./config:/etc/inboxapp
        command: bin/inbox-api
    redis:
        image: redis
    db1:
        image: mysql
        volumes:
            - db1_data:/var/lib/mysql
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: root
    db2:
        image: mysql
        volumes:
            - db1_data:/var/lib/mysql
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: root
