version: "2"
volumes:
    db_data:
        external: false
    inbox_data:
        external: false
services:
    engine:
        image: kevinjqiu/nylas-sync-engine
        links:
            - redis:redis
            - db:db
        volumes:
            - ./sync-engine:/app
            - inbox_data:/var/lib/inboxapp
            - ./config:/etc/inboxapp
        command: sh -c "/bin/wait-for-mysql.sh && bin/create-db || true && bin/inbox-start"
    api:
        image: kevinjqiu/nylas-sync-engine
        links:
            - redis:redis
            - db:db
        depends_on:
            - engine
        ports:
            - "5555:5555"
        volumes:
            - ./sync-engine:/app
            - inbox_data:/var/lib/inboxapp
            - ./config:/etc/inboxapp
        command: bin/inbox-api
    redis:
        image: redis
    db:
        image: mysql
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: root
